kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: go-app-multi-cluster
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: gitrepo-auth-kb2mc
  repo: https://github.com/NicoOosterwijk/private-repo.git
  paths:
  - multi-cluster
  targets:
  - name: speeltuin
    clusterSelector:
      matchLabels:
        name: speeltuin
  - name: raspberry-pi
    clusterName: raspberry-pi
