kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: go-app
  namespace: fleet-default
spec:
  repo: https://github.com/NicoOosterwijk/private-repo.git
  #repo: https://github.com/rancher/fleet-examples
  paths:
  - multi-cluster
  targets:
  - name: speeltuin
    clusterSelector:
      matchLabels:
        name: speeltuin
  - name: raspberry-pi
    clusterName: raspberry-pi
