---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibmljb29vc3RlcndpamsiLCJwYXNzd29yZCI6ImdocF9KYmhUZWtCcG9aOWw0STFOTHRiOWJGWVdabEpVb3gxT3ZDckwiLCJlbWFpbCI6Im5pY29AZGlnaXRhbGluZm8ubmwiLCJhdXRoIjoiYm1samIyOXZjM1JsY25kcGFtczZaMmh3WDBwaWFGUmxhMEp3YjFvNWJEUkpNVTVNZEdJNVlrWlpWMXBzU2xWdmVERlBka055VEE9PSJ9fX0=
type: kubernetes.io/dockerconfigjson