---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-rpi
  namespace: go-app
spec:
  template:
    spec:
      containers:
      - name: go-app
        image: registry.digitalinfo.nl/docker-hub/nokkie/app:2.0
